### ISSUE TITLE
Survey skip logic

### ISSUE THREAD

**Issue by Lu-vam** [instedd/aida#131]
We are encountering problems when we run susrveys with skip logic. Please see image and xlsx form attached.

![image](https://user-images.githubusercontent.com/36440133/37356182-b0934558-26e5-11e8-8c37-4dc919d86301.png)

[aJVvhmJMdT2zh5j26azMVy (7).xlsx](https://github.com/instedd/aida/files/1807842/aJVvhmJMdT2zh5j26azMVy.7.xlsx)

**Comment by nditada** [comment]
@Lu-vam it looks to me like the issue is not with skip logic but with the casing of the options. Your xlsform has a Label for "Yes" and you are answering "yes", since that's not a valid answer it is repeating the question. 

We should make sure to be case-insensitive, but a quick work around for now would be to add both options "Yes" and "yes". Can you try that please?

**Comment by Lu-vam** [comment]
Hi @nditada and @mmuller unfortunately I am not being able to check because today it is not possible to upload any change to the bot (neither on our server nor on your server)... problem as reported here: https://github.com/instedd/aida/issues/132 but lasting several hours this time.

**Comment by Lu-vam** [comment]
This might be related? 
![image](https://user-images.githubusercontent.com/36440133/37471610-7c44c26e-286a-11e8-8c4d-8ef213713a7f.png)

**Comment by waj** [comment]
@Lu-vam the stability of the server should have been restored by now. You should be able to try again.

Actually the case of the label is not the problem here, but a extra space added after the "Yes" label. If you remove that space it should work no matter the case of the answer given by the user. We should ignore that space and make it work anyway, but let's open a separate issue for that.

**Comment by nditada** [comment]
@Lu-vam the issue last time was due to a space after the "yes " in the xlsform. Can you make sure that's not the case this time? Can you share the xlsform and the manifest here so that we can take a look?

**Comment by nditada** [comment]
@Lu-vam I'm using the xlsform you sent over email and I can reproduce the behavior you describe.

However, the survey question "please provide your household number" has a "relevant" field with "${bamba_number} != '' and ${bamba_number} != 'no'", so the behavior is correct, that's the first question that matches the relevant condition. 

The line "Unfortunately, we are not able..."  also matches the conditions, but it's coming AFTER the previous one. I'm not sure why Kobo might be displaying that one before.

A simple solution for this would be to add an extra condition to the question you DO NOT want to be displayed ("please provide your ...") with "${bamba_problem_type} != '1'.
