### ISSUE TITLE
Better error reporting to user

### ISSUE THREAD

**Issue by nditada** [instedd/aida#141]
...when manifest is invalid and the preview or publication fails.

**Comment by jkicillof** [comment]
Errors should be traceable through the navigation https://projects.invisionapp.com/d/main#/console/12115078/268267947/comments

**Comment by nekron** [comment]
We need a better error reporting to the client itself. If the schema validation fails, we need to identify the failing step and try to match it with the corresponding type until we know for sure what the error really is. That way the client will be able to mark the exact error.

As a bonus, it would be great to check for runtime parsing errors, such as invalid expressions or date formats and report them to the client. It would be great to know which part of the expression is invalid. I.e. using `==` instead of `=` for comparisons.
