### ISSUE TITLE
Validate that Skills have a message

### ISSUE THREAD

**Issue by nditada** [instedd/aida#145]
At least decision trees are able to be saved without a message. I don't think that's useful in any situation. others?

**Comment by vtiffenberg** [comment]
I've been looking into what kind of validation we could do for this and they don't seem to make any sense:
- If the idea of the UI is that everything is saved on the fly and everything can be a draft, starting with an error message and or red font to indicate that X, Y and Z cannot be empty is counter productive
- Determining from the back end that a Skill is invalid if incomplete and not allowing it to save is also counter productive
- What should be done is being more clear about WHY the bot cannot be published, listing empty messages in skills as one of those reasons. This overlaps with #141 

For this ticket, I think I'll add the validation in the backend so that the bot can't be published, but it goes on the list of things that should be clarified when #141 comes along.

**Comment by mmuller** [comment]
Working properly in version 2496cdc
