### ISSUE TITLE
System command to get the session ID

### ISSUE THREAD

**Issue by nditada** [instedd/aida#148]
When users run into issues, it would be useful to be able to ask them to run a command and get the sessionID or a simpler version of it (last 4 chars?) so that we can easily find the session for diagnosis.

**Comment by nekron** [comment]
We could use the last 7 digits, as in git commits

**Comment by vtiffenberg** [comment]
@nekron for starters I have placed the functionality along with the RESET functionality, because I feel like they do very similar things: it's a functionality that all bots have, which is not visible or optional for the user. 
But the RESET code is located in the Facebook channel, and that doesn't feel right to me: wouldn't it make more sense that it were a Skill, added always when parsing a bot? It seems like it's out of the loop of abstractions right now, and would make it more so if more channels were added. (But I don't want to move anything before knowing there's logic on putting it before any message parsing can go wrong and fail). I'm pausing this until we can have a conversation.

**Comment by nekron** [comment]
The problem of that being a skill is that when there is an active survey expecting an answer, it will collide with the skill and the bot won't know what to do.

But I agree that we should move this to a higher scope and that we shouldn't have all this in the facebook channel.

I think that the best place to put it is in the bot itself. Just after the channel sends the message and before the skills take over.

Maybe we can have a different type of message generated by the channel: a system command, that gets handled in a particular way by the bot. Therefore unifying the logic but letting each channel implement this command according to their capabilities.

**Comment by mmuller** [comment]
Working properly in version 2496cdc
