### ISSUE TITLE
what is triggering the errors?

### ISSUE THREAD

**Issue by Lu-vam** [instedd/aida#258]
Hello, 

my bot is showing some errors and it cannot be tested/uploaded. I can't figure out what is triggering the errors  (some examples are provided in the images). Note that until few weeks ago this was working fine
 
![image](https://user-images.githubusercontent.com/36440133/44859183-e94aa580-ac73-11e8-81ce-1d35620cb7ca.png)
![image](https://user-images.githubusercontent.com/36440133/44859339-3a5a9980-ac74-11e8-9172-915b317e871e.png)
![image](https://user-images.githubusercontent.com/36440133/44859432-68d87480-ac74-11e8-8cdc-b39bf30c8643.png)

Could you help me?

Thanks, 
Lucia

**Comment by nekron** [comment]
Could you please tell me what's the bot Id? If you can include the url, it should be enough to identify it.

As I can see from the screenshots, "how much" is an invalid keyword as it contains spaces. See #252 and instedd/aida-ui#209

I'm not sure if it has more errors than that, I need to know the Id in order to properly debug it.

**Comment by Lu-vam** [comment]
Hello, this is the URL: https://aida.wfp.instedd.org/b/13/
Thanks!

**Comment by nekron** [comment]
As I can see, you still have some keywords containing spaces in two decision trees. 

"Bamba KES" decision tree has "kakuma 1", "kakuma 2", "kakuma 3",  and "kakuma 4" as possible answers to the first question of "Where do you live?".

Both "Bamba KES" and "GFD rations" decision trees have "size 1", "size 3", "size 4"... "size 20" as possible answers to the "What is your household size?" question.
